name: A Bigger Picture
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47713
title: a bigger picture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a1ada3'
    - '#fafeff'
    - '#7f8a86'
    - '#040000'
    - '#d5d3c7'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
