name: A Bigger Picture
favicon: null
layout_spectrum: 0.620436618803069
typography_spectrum: 0.10355118941515684
title: a bigger picture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#020202'
    - '#7d7d7d'
    - '#616161'
    - '#393939'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
