name: A Bigger Picture
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47713
title: a bigger picture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c7c7c'
    - '#505050'
    - '#cdcdcd'
    - '#080808'
    - '#acacac'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
