name: A Bigger Picture
favicon: null
layout_spectrum: 0.18973
typography_spectrum: 0.47713
title: a bigger picture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#020202'
    - '#7d7d7d'
    - '#616161'
    - '#393939'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
